#! /bin/sh
# /etc/init.d/provisionDeviceService

case "$1" in
  start)
    /usr/bin/node /home/pi/node-dps/register.js
    ;;
  stop)
    killall -9 node
    ;;
  *)
    echo "Usage: /etc/init.d/provisionDeviceService {start|stop}"
    exit 1
    ;;
esac
exit 0